name: stupid test

description: stupid action to test env variables

runs:
  using: composite
  steps:

    - name: define env variables
      shell: bash
      run: |
        echo "harbor_token=${{ github.token }}" >> "$GITHUB_ENV"
        echo "harbor_user=Jeannot" >> "$GITHUB_ENV"
        echo "harbor token: ${{ env.harbor_token }}"
        echo "harbor user: ${{ env.harbor_user }}"

    - name: use env variables
      shell: bash
      run: |
        echo "harbor token: ${{ env.harbor_token }}"
        echo "harbor user: ${{ env.harbor_user }}"

    - name: use functions
      shell: bash
      run: |
        function my_fn() {
          echo $harbor_user
        }
        
        export harbor_user=seb
        my_fn
        
        export harbor_user=jack
        my_fn
        
        export harbor_user=${{ github.token }}
        my_fn
