name: Java compile with Maven

on:

  workflow_call:
    inputs:
      java-version:
        type: string
        description: Required JDK version
        required: true
      distribution:
        type: string
        required: false
        default: 'temurin'
      skip-integration-tests:
        type: boolean
        description: Allows to skip integration tests (can be useful when working on a feature branch)
        required: false
        default: false
      run-package:
        type: boolean
        description: is running "mvn package" required ?
        required: false
        default: false

jobs:

  java-build:
    runs-on: ubuntu-latest
    env:
      # required to authenticate to GitHub mvn repo
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ inputs.java-version }}
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          cache: maven

      - name: Force all maven dependencies download for caching
        if: ${{ steps.setup-java.outputs.cache-hit == 'false' }}
        run: mvn -B dependency:go-offline

      - name: Compile main code
        run: mvn -B compile -Dmaven.test.skip=true

      - name: Compile test code
        run: mvn -B test-compile

      - name: Run unit tests
        run: mvn -B test -Dskip.IT=true

      - name: Run integration test
        if: ${{ inputs.skip-integration-tests == false }}
        run: mvn -B verify -Dskip.UT=true

      - name: Code quality analysis with SonarCloud
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar

      - name: Package
        if: ${{ inputs.run-package == true }}
        run: mvn -B package -DskipTests=true
