name: Java compile with Maven

on:

  workflow_call:
    inputs:
      java-version:
        type: string
        description: Required JDK version
        required: true
      distribution:
        type: string
        required: false
        default: temurin
      skip-integration-tests:
        type: boolean
        description: Allows to skip integration tests (can be useful when working on a feature branch)
        required: false
        default: false


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          cache: maven

      - name: Force all maven dependencies download for caching
        run: mvn -B dependency:go-offline

      - name: Compile main code
        run: mvn -B compile -Dmaven.test.skip=true

      - name: Compile main code
        run: mvn -B test-compile

      - name: Unit tests
        run: mvn -B test -DskipITs=true

      - name: Integration test
        if: ${{ !inputs.skip-integration-tests }}
        run: mvn -B failsafe:integration-test

      - name: Package
        run: mvn -B package -DskipTests=true
