name: stupid workflow

on:
  workflow_dispatch:

jobs:

  define_sites:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        name: "coucou"
        run: |
          echo "sites=['a', 'b']" >> "$GITHUB_OUTPUT"

  truc:
    runs-on: ubuntu-latest
    needs: define_sites
    #strategy:
      #matrix:
        #site: ${{ needs.define_sites.outputs.sites }}
    steps:
      - name: poulet
        shell: bash
        run: |
          echo ${{ needs.define_sites.outputs.sites }}