name: stupid workflow

on:
  workflow_dispatch:

jobs:

  define_sites:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        name: "coucou"
        run: |
          echo "sites=['a', 'b']" >> "$GITHUB_OUTPUT"

  truc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: ${{ jobs.define_sites.outputs.sites }}
    steps:
      - name: ${{ matrix.site }}
        shell: bash
        run: |
          echo ${{ matrix.site }}