name: stupid workflow

on:
  workflow_dispatch:

jobs:

  define_sites:
    runs-on: ubuntu-latest
    outputs:
      sites: ${{ steps.coucou.outputs.sites }}
    steps:
      - shell: bash
        name: "coucou"
        id: coucou
        run: |
          sites=""
          for site in a b c
          do
            sites="${sites} \"$site\""
          done
          
          sites_array=($(echo "$sites"))
          # write the elements of the bash array with ',' as separator (IFS = internal field separator)
          sites_json="[ $(IFS=',' ; echo "${sites_array[*]}") ]"
          echo "sites=$sites_json" >> "$GITHUB_OUTPUT"

  truc:
    runs-on: ubuntu-latest
    needs: define_sites
    strategy:
      matrix:
        #site: ${{ fromJSON( needs.define_sites.outputs.sites) }}
        site: ${{ needs.define_sites.outputs.sites }}
    steps:
      - name: poulet
        shell: bash
        run: |
          echo ${{ matrix.site }}